language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: vN9qqLdaO9sfGRA9Q0v9hLcokpq2FycKekTvr0uuIiIJYG3aLUzrgPoU6qIWVnBpwA6bjZaRDMqhfj9dD+uFQQBOOqkX2YwQ455gvqYM4s6QlQexNyliiL8aamvmAnXAIhaiJsMxq2yArW5qh84YKMTIKu4j/LLsCcmiPulGOBEldKc/WKlIXrAg2RzC8YIo/e7YmabpIcByEg6Lxw/8EeW/+MwwpoUs67dwfv6EJ29qZ5eL75LwMi85xFS3yJdKiMwSbLr9+HfG78w61wPpADlMQkADEWXoAR2zrPIWBhKMc2UqBK9fj5QbwAcgStUX4usGA5YNnlUahL0iFIPuMEVcD0UnBzF6832N8+XQ+LeEpzTXCdPefYA6zyZGgih0PQ9dh86qHNic6LHZy+FDC0d2Y7nPOX6vEiVQjNjvx1k7yZGwNEKAglqG+FMIwXpIFiC2VwJHkE16iqx6xviIXJ1RyuDzAquaByAf+cXkt7tR6KgJMZ43x/8Ife1srN1aMHgcP2vxCrjdj9onfrMU8xYQ6wU5gOWkalxlQ5vOOp/aUza1i98F8uQnNmzEQyTzg2SANEgzsikv/zPNfxmvBE/mSpmmCwj3lMh5g4lIhElxMowJ6paVSlklxBS4gpMo9G8ZrQ+9aZ9+DsR8AoUH1Gb9nPoJARpUHRsdl2p5log=
php:
- 5.3
- 5.6
- 7.0
- 7.1
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=trunk WP_MULTISITE=0
- WP_VERSION=3.8 WP_MULTISITE=0
- WP_VERSION=4.2 WP_MULTISITE=0
matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
  - php: 7.0
    env: WP_VERSION=3.8 WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install --dev
script: phpunit
